  CREATE TABLE "OWNERS"
   (	"ID" NUMBER(19,0) NOT NULL ENABLE,
	"ADDRESS" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"CITY" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"FIRST_NAME" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"LAST_NAME" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"TELEPHONE" VARCHAR2(10 CHAR) NOT NULL ENABLE,
	 PRIMARY KEY ("ID"));
