CREATE TABLE "VISITS" (
	"ID" NUMBER(19,0) NOT NULL ENABLE,
	"VISIT_DATE" DATE NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(255) NOT NULL ENABLE,
	"PET_ID" NUMBER(19,0) NOT NULL ENABLE,
	 PRIMARY KEY ("ID"),
	 CONSTRAINT "FK_VISITS_PET" FOREIGN KEY ("PET_ID") REFERENCES "PETS" ("ID") ENABLE
);
